# Generated by Django 2.2.10 on 2020-03-02 17:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('image', models.BinaryField(default=b'\x80\x03N.')),
                ('rects', django.contrib.postgres.fields.jsonb.JSONField()),
                ('lot_id', models.IntegerField()),
            ],
        ),
    ]
