# Generated by Django 2.2.10 on 2020-02-11 13:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import kafka_consumer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', kafka_consumer.models.AutoDateTimeField()),
                ('rects', django.contrib.postgres.fields.jsonb.JSONField()),
                ('lot_id', models.IntegerField()),
            ],
        ),
    ]
