# Generated by Django 2.2.10 on 2020-03-02 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LotModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='DetectorResult',
            new_name='SpotterModel',
        ),
        migrations.CreateModel(
            name='LotStateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_spots', models.IntegerField()),
                ('available_spots', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('lot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafka_consumer.LotModel')),
            ],
        ),
    ]
