# Generated by Django 2.2.10 on 2020-03-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0002_auto_20200302_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spottermodel',
            name='lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafka_consumer.LotModel'),
        ),
    ]
