# Generated by Django 2.2.10 on 2020-03-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0003_auto_20200302_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='spottermodel',
            name='image_file',
            field=models.FileField(default='', upload_to='lot_images/'),
        ),
    ]
