# Generated by Django 2.2.10 on 2020-03-18 18:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0004_spottermodel_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotstatemodel',
            name='rects',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None),
        ),
        migrations.CreateModel(
            name='SettingsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ttl_to_accept', models.IntegerField(default=30)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafka_consumer.LotModel')),
            ],
        ),
    ]
