# Generated by Django 2.2.10 on 2020-03-18 18:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0006_auto_20200318_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotstatemodel',
            name='rects',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
