# Generated by Django 2.2.10 on 2020-03-24 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0008_auto_20200318_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpotModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField()),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafka_consumer.LotModel')),
            ],
        ),
        migrations.CreateModel(
            name='SpotHistoryModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kafka_consumer.ParkingSpotModel')),
            ],
        ),
    ]
