# Generated by Django 2.2.10 on 2020-03-24 09:17

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0009_parkingspotmodel_spothistorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspotmodel',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='spothistorymodel',
            name='ttl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='spothistorymodel',
            name='status',
            field=models.IntegerField(default=-1),
        ),
    ]
