# Generated by Django 2.2.10 on 2020-03-24 09:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0010_auto_20200324_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspotmodel',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
