# Generated by Django 2.2.10 on 2020-03-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0012_auto_20200324_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spothistorymodel',
            name='status',
        ),
    ]
