# Generated by Django 2.2.10 on 2020-03-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0014_spothistorymodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spothistorymodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='spothistorymodel',
            name='ttl',
        ),
        migrations.AddField(
            model_name='parkingspotmodel',
            name='status',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='parkingspotmodel',
            name='ttl',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parkingspotmodel',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
