# Generated by Django 2.2.10 on 2020-03-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0015_auto_20200324_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspotmodel',
            name='ttl',
            field=models.FloatField(default=0.0),
        ),
    ]
