# Generated by Django 2.2.10 on 2020-04-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0018_auto_20200329_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spottermodel',
            name='lot_id',
        ),
        migrations.DeleteModel(
            name='LotStateModel',
        ),
        migrations.DeleteModel(
            name='SpotterModel',
        ),
    ]
