# Generated by Django 2.2.10 on 2020-05-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0019_auto_20200423_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotmodel',
            name='video_src',
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settingsmodel',
            name='video_src',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
