# Generated by Django 2.2.10 on 2020-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafka_consumer', '0020_auto_20200505_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settingsmodel',
            name='video_src',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
