TOPIC_DETECT = "topic.detector"
TOPIC_SLICE = "topic.slicer"
TOPIC_IMAGE = "topic.slicer"
TOPIC_BACKEND_BASE = "topic.backend."
TOPIC_BACKEND = TOPIC_BACKEND_BASE+"0"
TOPIC_SPOT = "topic.spot"
TOPIC_STATUS = "topic.status"
